server:
  port: 8761 #1 当前Eureka Server服务的端口号为8761
eureka:
  instance:
    hostname: localhost #2 当前Eureka Server的hostname为localhost
  client:
    register-with-eureka: false #3 当前服务部需要到Eureka Server上注册
    fetch-registry: false

