#server:
#  port: 8762
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://117.30.224.251:3306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&useSSL=false
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  rabbitmq:
#    host: 117.30.224.251
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirms: true
#    virtual-host: /